import type { Metadata } from "next";
import { Hubot_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const hubotSans = Hubot_Sans({
  variable: "--font-hubot-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trimly Barber Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${hubotSans.variable} antialiased`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
